"""HTML dashboard report generation for Coyote scan results."""

from __future__ import annotations

import html
from datetime import datetime, timezone

from .patterns import Severity
from .scanner import ScanResult


def generate_html_report(result: ScanResult, commit_hash: str = "") -> str:
    """Generate a self-contained HTML dashboard report."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    findings_rows = _build_findings_rows(result)
    chart_css = _build_donut_chart_css(result)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Coyote Security Report</title>
<style>
{_CSS}
{chart_css}
</style>
</head>
<body>

<header>
  <div class="brand">
    <h1>COYOTE</h1>
    <span class="subtitle">Security Scan Report</span>
  </div>
  <div class="meta">
    <span><strong>Repository:</strong> {html.escape(result.repo_path)}</span>
    {f'<span><strong>Commit:</strong> <code>{html.escape(commit_hash[:12])}</code></span>' if commit_hash else ''}
    <span><strong>Date:</strong> {timestamp}</span>
  </div>
</header>

<section class="summary-cards">
  <div class="card card-total">
    <div class="card-value">{result.total_count}</div>
    <div class="card-label">Total Findings</div>
  </div>
  <div class="card card-high">
    <div class="card-value">{result.high_count}</div>
    <div class="card-label">High</div>
  </div>
  <div class="card card-medium">
    <div class="card-value">{result.medium_count}</div>
    <div class="card-label">Medium</div>
  </div>
  <div class="card card-low">
    <div class="card-value">{result.low_count}</div>
    <div class="card-label">Low</div>
  </div>
</section>

{_build_chart_section(result)}

{_build_findings_section(result, findings_rows)}

<footer>
  <div class="stats">
    <span>Files scanned: <strong>{result.files_scanned}</strong></span>
    <span>Files skipped: <strong>{result.files_skipped}</strong></span>
    {f'<span>Findings suppressed: <strong>{result.findings_suppressed}</strong></span>' if result.findings_suppressed > 0 else ''}
  </div>
  <div class="generated">Generated by Coyote</div>
</footer>

<script>
{_JS}
</script>
</body>
</html>"""


def _build_findings_rows(result: ScanResult) -> str:
    if not result.findings:
        return ""

    severity_order = {Severity.HIGH: 0, Severity.MEDIUM: 1, Severity.LOW: 2}
    sorted_findings = sorted(result.findings, key=lambda f: severity_order.get(f.severity, 3))

    rows = []
    for f in sorted_findings:
        sev = f.severity.value
        sev_class = sev.lower()
        loc = html.escape(f.file_path)
        if f.line_number > 0:
            loc += f":{f.line_number}"
        matched = html.escape(f.matched_text) if f.matched_text else "&mdash;"
        rows.append(
            f'<tr class="severity-{sev_class}" data-severity="{sev_class}">'
            f'<td><span class="badge badge-{sev_class}">{sev}</span></td>'
            f"<td><code>{html.escape(f.finding_id)}</code></td>"
            f"<td>{html.escape(f.rule_name)}</td>"
            f"<td><code>{loc}</code></td>"
            f"<td>{html.escape(f.description)}</td>"
            f"<td><code>{matched}</code></td>"
            f"</tr>"
        )
    return "\n".join(rows)


def _build_chart_section(result: ScanResult) -> str:
    if result.total_count == 0:
        return ""
    return """<section class="chart-section">
  <h2>Severity Breakdown</h2>
  <div class="donut-container">
    <div class="donut"></div>
    <div class="donut-legend">
      <div class="legend-item"><span class="dot dot-high"></span> High</div>
      <div class="legend-item"><span class="dot dot-medium"></span> Medium</div>
      <div class="legend-item"><span class="dot dot-low"></span> Low</div>
    </div>
  </div>
</section>"""


def _build_findings_section(result: ScanResult, rows: str) -> str:
    if result.total_count == 0:
        return """<section class="findings-section">
  <div class="all-clear">
    <div class="all-clear-icon">&#10003;</div>
    <h2>All Clear</h2>
    <p>No security issues found.</p>
  </div>
</section>"""

    return f"""<section class="findings-section">
  <h2>Findings</h2>
  <div class="filters">
    <button class="filter-btn filter-high active" data-severity="high">HIGH ({result.high_count})</button>
    <button class="filter-btn filter-medium active" data-severity="medium">MEDIUM ({result.medium_count})</button>
    <button class="filter-btn filter-low active" data-severity="low">LOW ({result.low_count})</button>
  </div>
  <div class="table-wrapper">
    <table>
      <thead>
        <tr>
          <th>Severity</th>
          <th>ID</th>
          <th>Rule</th>
          <th>Location</th>
          <th>Description</th>
          <th>Match</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
  </div>
</section>"""


def _build_donut_chart_css(result: ScanResult) -> str:
    total = result.total_count
    if total == 0:
        return ""
    h = (result.high_count / total) * 100
    m = (result.medium_count / total) * 100
    # low fills the remainder
    return f""".donut {{
  background: conic-gradient(
    #e74c3c 0% {h:.1f}%,
    #f39c12 {h:.1f}% {h + m:.1f}%,
    #3498db {h + m:.1f}% 100%
  );
}}"""


_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
  background: #1a1a2e;
  color: #e0e0e0;
  line-height: 1.6;
  padding: 2rem;
}
code {
  background: rgba(255,255,255,0.08);
  padding: 0.15em 0.4em;
  border-radius: 3px;
  font-size: 0.9em;
}
header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid #2a2a4a;
  margin-bottom: 2rem;
  flex-wrap: wrap;
  gap: 1rem;
}
.brand h1 {
  font-size: 2rem;
  letter-spacing: 0.3em;
  color: #f39c12;
}
.subtitle {
  color: #888;
  font-size: 0.9rem;
}
.meta {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 0.25rem;
  font-size: 0.85rem;
  color: #aaa;
}
.summary-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}
.card {
  background: #16213e;
  border-radius: 8px;
  padding: 1.25rem;
  text-align: center;
  border-left: 4px solid #444;
}
.card-value {
  font-size: 2.5rem;
  font-weight: 700;
}
.card-label {
  font-size: 0.85rem;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}
.card-total { border-left-color: #888; }
.card-total .card-value { color: #fff; }
.card-high { border-left-color: #e74c3c; }
.card-high .card-value { color: #e74c3c; }
.card-medium { border-left-color: #f39c12; }
.card-medium .card-value { color: #f39c12; }
.card-low { border-left-color: #3498db; }
.card-low .card-value { color: #3498db; }

.chart-section {
  margin-bottom: 2rem;
}
.chart-section h2 {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  color: #ccc;
}
.donut-container {
  display: flex;
  align-items: center;
  gap: 2rem;
}
.donut {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  position: relative;
}
.donut::after {
  content: "";
  position: absolute;
  top: 30px;
  left: 30px;
  width: 60px;
  height: 60px;
  background: #1a1a2e;
  border-radius: 50%;
}
.donut-legend {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
.legend-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.9rem;
}
.dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  display: inline-block;
}
.dot-high { background: #e74c3c; }
.dot-medium { background: #f39c12; }
.dot-low { background: #3498db; }

.findings-section {
  margin-bottom: 2rem;
}
.findings-section h2 {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  color: #ccc;
}
.filters {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}
.filter-btn {
  padding: 0.4rem 1rem;
  border: 1px solid #444;
  background: transparent;
  color: #888;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.8rem;
  font-weight: 600;
  letter-spacing: 0.05em;
  transition: all 0.15s;
}
.filter-btn:hover { border-color: #666; color: #ccc; }
.filter-btn.active.filter-high { border-color: #e74c3c; color: #e74c3c; background: rgba(231,76,60,0.1); }
.filter-btn.active.filter-medium { border-color: #f39c12; color: #f39c12; background: rgba(243,156,18,0.1); }
.filter-btn.active.filter-low { border-color: #3498db; color: #3498db; background: rgba(52,152,219,0.1); }
.table-wrapper {
  overflow-x: auto;
}
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.85rem;
}
thead th {
  text-align: left;
  padding: 0.75rem 0.5rem;
  border-bottom: 2px solid #2a2a4a;
  color: #999;
  font-weight: 600;
  text-transform: uppercase;
  font-size: 0.75rem;
  letter-spacing: 0.05em;
}
tbody td {
  padding: 0.6rem 0.5rem;
  border-bottom: 1px solid #2a2a4a;
  vertical-align: top;
}
tbody tr:hover { background: rgba(255,255,255,0.03); }
tbody tr.hidden { display: none; }
.badge {
  padding: 0.15em 0.5em;
  border-radius: 3px;
  font-size: 0.75rem;
  font-weight: 700;
}
.badge-high { background: rgba(231,76,60,0.2); color: #e74c3c; }
.badge-medium { background: rgba(243,156,18,0.2); color: #f39c12; }
.badge-low { background: rgba(52,152,219,0.2); color: #3498db; }

.all-clear {
  text-align: center;
  padding: 3rem;
  color: #2ecc71;
}
.all-clear-icon {
  font-size: 3rem;
  margin-bottom: 0.5rem;
}
.all-clear h2 {
  color: #2ecc71;
  margin-bottom: 0.5rem;
}
.all-clear p { color: #888; }

footer {
  margin-top: 2rem;
  padding-top: 1.5rem;
  border-top: 1px solid #2a2a4a;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;
}
.stats {
  display: flex;
  gap: 1.5rem;
  font-size: 0.85rem;
  color: #888;
}
.generated {
  font-size: 0.8rem;
  color: #555;
}
"""

_JS = """
document.querySelectorAll('.filter-btn').forEach(function(btn) {
  btn.addEventListener('click', function() {
    btn.classList.toggle('active');
    var sev = btn.getAttribute('data-severity');
    var rows = document.querySelectorAll('tr[data-severity="' + sev + '"]');
    var show = btn.classList.contains('active');
    rows.forEach(function(row) {
      row.classList.toggle('hidden', !show);
    });
  });
});
"""
