"""Security detection patterns for Coyote scanner."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Severity(Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


@dataclass
class PatternMatch:
    rule_name: str
    severity: Severity
    file_path: str
    line_number: int
    line_content: str
    description: str
    matched_text: str = ""
    finding_id: str = ""  # Stable ID for diffing/suppression, generated by scanner
    remediation: str = ""  # Actionable fix guidance
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass
class SecretPattern:
    name: str
    pattern: re.Pattern
    severity: Severity
    description: str
    remediation: str = ""
    near_context: Optional[re.Pattern] = None  # require nearby context


# --- Secrets & Credentials ---

SECRET_PATTERNS: list[SecretPattern] = [
    SecretPattern(
        name="AWS Access Key",
        pattern=re.compile(r'AKIA[0-9A-Z]{16}'),
        severity=Severity.HIGH,
        description="AWS Access Key ID detected",
        remediation="Rotate this key in the AWS IAM console and use environment variables or a secrets manager instead.",
    ),
    SecretPattern(
        name="AWS Secret Key",
        pattern=re.compile(r'(?<![A-Za-z0-9/+])[0-9a-zA-Z/+]{40}(?![A-Za-z0-9/+=])'),
        severity=Severity.HIGH,
        description="Possible AWS Secret Access Key detected",
        remediation="Rotate this secret in AWS IAM and store it in a secrets manager (e.g., AWS Secrets Manager, HashiCorp Vault).",
        near_context=re.compile(r'(?i)(aws|amazon|secret.?access|secret.?key)', re.IGNORECASE),
    ),
    SecretPattern(
        name="GitHub Token",
        pattern=re.compile(r'gh[pousr]_[A-Za-z0-9_]{36,}'),
        severity=Severity.HIGH,
        description="GitHub personal access token detected",
        remediation="Revoke this token at github.com/settings/tokens and generate a new one with minimal scopes. Store it in environment variables.",
    ),
    SecretPattern(
        name="GitLab Token",
        pattern=re.compile(r'glpat-[A-Za-z0-9\-]{20,}'),
        severity=Severity.HIGH,
        description="GitLab personal access token detected",
        remediation="Revoke this token in GitLab > Preferences > Access Tokens and store the replacement in environment variables.",
    ),
    SecretPattern(
        name="Slack Token",
        pattern=re.compile(r'xox[baprs]-[0-9A-Za-z\-]+'),
        severity=Severity.HIGH,
        description="Slack API token detected",
        remediation="Regenerate this token in your Slack app settings and store it in environment variables.",
    ),
    SecretPattern(
        name="Slack Webhook",
        pattern=re.compile(r'https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[a-zA-Z0-9]+'),
        severity=Severity.HIGH,
        description="Slack webhook URL detected",
        remediation="Rotate this webhook URL in Slack app settings and store it in environment variables.",
    ),
    SecretPattern(
        name="Discord Webhook",
        pattern=re.compile(r'https://discord(?:app)?\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+'),
        severity=Severity.HIGH,
        description="Discord webhook URL detected",
        remediation="Regenerate this webhook in Discord channel settings and store it in environment variables.",
    ),
    SecretPattern(
        name="OpenAI Key",
        pattern=re.compile(r'sk-[A-Za-z0-9]{48}'),
        severity=Severity.HIGH,
        description="OpenAI API key detected",
        remediation="Rotate this key at platform.openai.com/api-keys and store it in environment variables.",
    ),
    SecretPattern(
        name="Anthropic Key",
        pattern=re.compile(r'sk-ant-[A-Za-z0-9\-_]{90,}'),
        severity=Severity.HIGH,
        description="Anthropic API key detected",
        remediation="Rotate this key at console.anthropic.com/settings/keys and store it in environment variables.",
    ),
    SecretPattern(
        name="Stripe Live Key",
        pattern=re.compile(r'(?:sk|rk)_live_[A-Za-z0-9]{24,}'),
        severity=Severity.HIGH,
        description="Stripe live API key detected",
        remediation="Roll this key in the Stripe Dashboard under Developers > API keys. Use environment variables in production.",
    ),
    SecretPattern(
        name="Twilio API Key",
        pattern=re.compile(r'SK[a-f0-9]{32}'),
        severity=Severity.HIGH,
        description="Twilio API key detected",
        remediation="Rotate this key in the Twilio Console and store the replacement in environment variables.",
    ),
    SecretPattern(
        name="SendGrid Key",
        pattern=re.compile(r'SG\.[A-Za-z0-9\-_]{22}\.[A-Za-z0-9\-_]{43}'),
        severity=Severity.HIGH,
        description="SendGrid API key detected",
        remediation="Revoke this key in the SendGrid dashboard and store the replacement in environment variables.",
    ),
    SecretPattern(
        name="Google API Key",
        pattern=re.compile(r'AIza[0-9A-Za-z\-_]{35}'),
        severity=Severity.HIGH,
        description="Google API key detected",
        remediation="Regenerate this key in the Google Cloud Console and restrict it to specific APIs and referrers.",
    ),
    SecretPattern(
        name="Private Key",
        pattern=re.compile(r'-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH|PGP)\s+PRIVATE\s+KEY-----'),
        severity=Severity.HIGH,
        description="Private key block detected",
        remediation="Remove this private key from the repository, generate a new key pair, and store the private key outside version control.",
    ),
    SecretPattern(
        name="Generic Secret",
        pattern=re.compile(
            r'''(?i)(?:password|passwd|secret|api_key|apikey|access_token|auth_token|private_key)'''
            r'''[\s]*[=:]\s*['"][^'"]{8,}['"]'''
        ),
        severity=Severity.HIGH,
        description="Hardcoded secret/password assignment detected",
        remediation="Move this secret to environment variables or a secrets manager. Never hardcode secrets in source files.",
    ),
    SecretPattern(
        name="JWT Token",
        pattern=re.compile(r'eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'),
        severity=Severity.HIGH,
        description="JSON Web Token detected",
        remediation="Remove this token from source code. JWTs should be generated at runtime, not embedded in code.",
    ),
    SecretPattern(
        name="Basic Auth URL",
        pattern=re.compile(r'https?://[^:\s]+:[^@\s]+@'),
        severity=Severity.HIGH,
        description="URL with embedded credentials detected",
        remediation="Remove credentials from the URL. Use environment variables for authentication parameters.",
    ),
]


# --- Sensitive Files ---

SENSITIVE_FILE_PATTERNS: list[tuple[str, str, Severity]] = [
    # (glob pattern, description, severity)
    (".env", "Environment file with potential secrets", Severity.HIGH),
    (".env.local", "Local environment file", Severity.HIGH),
    (".env.production", "Production environment file", Severity.HIGH),
    (".env.*", "Environment variant file", Severity.HIGH),
    ("*.pem", "PEM certificate/key file", Severity.HIGH),
    ("*.key", "Private key file", Severity.HIGH),
    ("*.p12", "PKCS#12 certificate file", Severity.HIGH),
    ("*.pfx", "PFX certificate file", Severity.HIGH),
    ("id_rsa", "RSA private key", Severity.HIGH),
    ("id_dsa", "DSA private key", Severity.HIGH),
    ("id_ed25519", "Ed25519 private key", Severity.HIGH),
    ("id_ecdsa", "ECDSA private key", Severity.HIGH),
    ("*.sql", "SQL dump file", Severity.MEDIUM),
    ("*.dump", "Database dump file", Severity.MEDIUM),
    ("*.sqlite", "SQLite database file", Severity.MEDIUM),
    ("*.db", "Database file", Severity.MEDIUM),
    ("*.bak", "Backup file", Severity.LOW),
    ("*.backup", "Backup file", Severity.LOW),
    ("*.old", "Old file backup", Severity.LOW),
    ("credentials.json", "Credentials file", Severity.HIGH),
    ("service-account*.json", "GCP service account key", Severity.HIGH),
    (".htpasswd", "Apache password file", Severity.HIGH),
    (".netrc", "Netrc credentials file", Severity.HIGH),
    (".npmrc", "NPM config (may contain auth tokens)", Severity.MEDIUM),
    ("terraform.tfstate", "Terraform state (may contain secrets)", Severity.HIGH),
    ("*.tfvars", "Terraform variables (may contain secrets)", Severity.MEDIUM),
]

# Patterns for matching sensitive filenames (compiled from the above)
SENSITIVE_FILENAME_EXACT: dict[str, tuple[str, Severity]] = {}
SENSITIVE_FILENAME_GLOBS: list[tuple[str, str, Severity]] = []

for _pat, _desc, _sev in SENSITIVE_FILE_PATTERNS:
    if "*" in _pat:
        SENSITIVE_FILENAME_GLOBS.append((_pat, _desc, _sev))
    else:
        SENSITIVE_FILENAME_EXACT[_pat] = (_desc, _sev)

SENSITIVE_FILE_REMEDIATION: dict[str, str] = {
    ".env": "Add .env to .gitignore and use a secrets manager for production credentials.",
    ".env.local": "Add .env.local to .gitignore and use a secrets manager for production credentials.",
    ".env.production": "Add .env.production to .gitignore and use a secrets manager for production credentials.",
    ".env.*": "Add .env.* to .gitignore and use a secrets manager for production credentials.",
    "*.pem": "Store certificates outside the repository and reference them via file paths in environment variables.",
    "*.key": "Store private keys outside the repository. Use a secrets manager or encrypted storage.",
    "*.p12": "Store certificates outside the repository. Use a secrets manager or encrypted storage.",
    "*.pfx": "Store certificates outside the repository. Use a secrets manager or encrypted storage.",
    "id_rsa": "Remove SSH keys from the repository. Generate new keys and add id_rsa to .gitignore.",
    "id_dsa": "Remove SSH keys from the repository. Generate new keys and add id_dsa to .gitignore.",
    "id_ed25519": "Remove SSH keys from the repository. Generate new keys and add id_ed25519 to .gitignore.",
    "id_ecdsa": "Remove SSH keys from the repository. Generate new keys and add id_ecdsa to .gitignore.",
    "*.sql": "Remove database dumps from the repository. Use secure backup storage instead.",
    "*.dump": "Remove database dumps from the repository. Use secure backup storage instead.",
    "*.sqlite": "Remove database files from the repository. Add *.sqlite to .gitignore.",
    "*.db": "Remove database files from the repository. Add *.db to .gitignore.",
    "credentials.json": "Store credentials outside the repository. Use a secrets manager and add this file to .gitignore.",
    "service-account*.json": "Store service account keys outside the repository. Use workload identity or a secrets manager.",
    ".htpasswd": "Remove this password file from the repository and add .htpasswd to .gitignore.",
    ".netrc": "Remove .netrc from the repository and add it to .gitignore. Use a credential helper instead.",
    ".npmrc": "Remove .npmrc from the repository if it contains auth tokens. Add it to .gitignore.",
    "terraform.tfstate": "Use remote state storage (e.g., S3 backend) instead of committing state files. Add to .gitignore.",
    "*.tfvars": "Add *.tfvars to .gitignore. Use environment variables or a secrets manager for sensitive Terraform variables.",
}
_SENSITIVE_FILE_REMEDIATION_DEFAULT = "Remove this file from the repository and add it to .gitignore."


def get_sensitive_file_remediation(filename: str) -> str:
    """Look up remediation for a sensitive file, checking exact then glob patterns."""
    if filename in SENSITIVE_FILE_REMEDIATION:
        return SENSITIVE_FILE_REMEDIATION[filename]
    import fnmatch as _fnmatch
    for pattern, remediation in SENSITIVE_FILE_REMEDIATION.items():
        if _fnmatch.fnmatch(filename, pattern):
            return remediation
    return _SENSITIVE_FILE_REMEDIATION_DEFAULT


# --- Security Smells ---

@dataclass
class SmellPattern:
    name: str
    pattern: re.Pattern
    severity: Severity
    description: str
    remediation: str = ""
    file_extensions: list[str] = field(default_factory=list)  # empty = all files


SMELL_PATTERNS: list[SmellPattern] = [
    SmellPattern(
        name="Debug Mode Enabled",
        pattern=re.compile(r'DEBUG\s*=\s*(?:True|true|1)'),
        severity=Severity.MEDIUM,
        description="Debug mode appears to be enabled",
        remediation="Set DEBUG=False for production deployments. Use environment-based configuration to toggle debug mode.",
        file_extensions=[".py", ".cfg", ".ini", ".conf", ".yaml", ".yml", ".toml", ".env"],
    ),
    SmellPattern(
        name="SSL Verification Disabled",
        pattern=re.compile(r'verify\s*=\s*False'),
        severity=Severity.MEDIUM,
        description="SSL certificate verification is disabled",
        remediation="Re-enable SSL verification (verify=True). Use proper CA certificates instead of disabling verification.",
        file_extensions=[".py"],
    ),
    SmellPattern(
        name="Node TLS Rejection Disabled",
        pattern=re.compile(r'''NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0'''),
        severity=Severity.MEDIUM,
        description="Node.js TLS certificate rejection is disabled",
        remediation="Remove NODE_TLS_REJECT_UNAUTHORIZED=0. Fix the underlying certificate issue instead.",
        file_extensions=[".js", ".ts", ".mjs", ".cjs", ".env"],
    ),
    SmellPattern(
        name="Permissive CORS",
        pattern=re.compile(r'Access-Control-Allow-Origin.*\*'),
        severity=Severity.MEDIUM,
        description="Overly permissive CORS configuration (allows all origins)",
        remediation="Restrict Access-Control-Allow-Origin to specific trusted domains instead of using wildcard (*).",
        file_extensions=[],
    ),
    SmellPattern(
        name="Eval Usage (JS)",
        pattern=re.compile(r'\beval\s*\('),
        severity=Severity.MEDIUM,
        description="Use of eval() poses code injection risk",
        remediation="Replace eval() with safer alternatives like JSON.parse() or a sandboxed interpreter.",
        file_extensions=[".js", ".ts", ".mjs", ".cjs", ".jsx", ".tsx"],
    ),
    SmellPattern(
        name="Eval Usage (Python)",
        pattern=re.compile(r'\beval\s*\('),
        severity=Severity.MEDIUM,
        description="Use of eval() poses code injection risk",
        remediation="Replace eval() with ast.literal_eval() for data parsing, or use safer alternatives.",
        file_extensions=[".py"],
    ),
    SmellPattern(
        name="dangerouslySetInnerHTML",
        pattern=re.compile(r'dangerouslySetInnerHTML'),
        severity=Severity.MEDIUM,
        description="dangerouslySetInnerHTML usage poses XSS risk",
        remediation="Sanitize HTML input with a library like DOMPurify before using dangerouslySetInnerHTML.",
        file_extensions=[".jsx", ".tsx", ".js", ".ts"],
    ),
    SmellPattern(
        name="Security Debt Marker",
        pattern=re.compile(r'(?i)(?:TODO|FIXME|HACK|XXX)\s*[:\-]?\s*(?:security|auth|password|secret|cred|vuln)'),
        severity=Severity.MEDIUM,
        description="Security-related TODO/FIXME comment found",
        remediation="Address this security TODO/FIXME. Track it in your issue tracker if it cannot be resolved immediately.",
        file_extensions=[],
    ),
    SmellPattern(
        name="Hardcoded Internal IP",
        pattern=re.compile(r'(?:192\.168\.|10\.\d+\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.)'),
        severity=Severity.MEDIUM,
        description="Hardcoded internal/private IP address detected",
        remediation="Use configuration files, environment variables, or service discovery instead of hardcoded IP addresses.",
        file_extensions=[],
    ),
    SmellPattern(
        name="Clawdbot GatewayUrl Query Override",
        pattern=re.compile(r'''(?i)(URLSearchParams\\(.*\\)\\.get\\(['"]gatewayUrl['"]\\)|gatewayurlsource\\s*[:=]\\s*['"]?(?:query|querystring|query_string|external))'''),
        severity=Severity.HIGH,
        description="Gateway URL override via query parameters can enable token exfiltration",
        remediation="Remove query parameter-based gateway URL override. Use a fixed, server-side configuration for gateway URLs.",
        file_extensions=[".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs", ".json", ".yaml", ".yml", ".toml"],
    ),
    SmellPattern(
        name="Clawdbot WebSocket Origin Not Validated",
        pattern=re.compile(r'''(?i)(origin_check\\s*[:=]\\s*(?:false|off|disabled)|allowed_origins\\s*[:=]\\s*['"]?\\*)'''),
        severity=Severity.HIGH,
        description="WebSocket origin validation is disabled or allows any origin",
        remediation="Enable WebSocket origin validation and restrict allowed_origins to trusted domains.",
        file_extensions=[".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs", ".json", ".yaml", ".yml", ".toml", ".env"],
    ),
]


# --- Git-Specific Checks ---

GITIGNORE_SHOULD_CONTAIN: list[str] = [
    ".env",
    "*.pem",
    "*.key",
    "id_rsa",
    "*.p12",
    "*.pfx",
    ".env.*",
    "*.sqlite",
    "*.db",
    "terraform.tfstate",
    "*.tfvars",
    "credentials.json",
]

# Max size in bytes for binary file warnings
LARGE_FILE_THRESHOLD = 10 * 1024 * 1024  # 10 MB
